### ISSUE TITLE
Setup BE application architecture

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v33-bears-team-10#20]
**__Task Description__**
Setup BE application architecture by setting up the BE repo

**__Technical Considerations__**
Detailed steps to follow depends on which FE framework is selected

**__Additional Considerations__**
TBD

**Comment by Aminy16** [comment]
@Beidah @egrivalsky do we have updates on this end?

**Comment by egrivalsky** [comment]
Typescript had slowed me up, but Hunter has been an invaluable resource. I
pushed a work in progress to the top25 working branch last night.  Just
have to review the basic  map function so I can get the data we want
