### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v33-bears-team-10#22]
**__User Story Description__**
As a end user
I want to see info that describes what the app does 
So I can be motivated to try it

**__Steps to Follow (optional)__**
- [x] Design & write the layout component
- [x] Design & write the app-hero
- [x] Design & write the quizz-hero
- [x] Design & write the data-hero
- [x] Design & write the about-team hero

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by angelopoole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Chingu-V33-Bears-10-61311f1b1d329e0020e0ef9c/issues/chingu-voyages/v33-bears-team-10/22?planning-poker) with ZenHub @Torja99 @egrivalsky @Beidah @andrewrametta @Aminy16

**Comment by Aminy16** [comment]
@angelopoole do you have any updates on this issue?

**Comment by Aminy16** [comment]
Do we need the team to add their votes?

**Comment by angelopoole** [comment]
> @angelopoole do you have any updates on this issue?
Quiz-hero and Layout are done, they could use some refactoring and style tuneups but they complete their intended jobs, 
I recommend opening up an issue for style enhancements that we can defer until we have functionality. 

I will have the rest of the landing page done by the end of the day.
