### ISSUE TITLE
Create FE hook for song playback

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v33-bears-team-10#33]
**__Task Description__**
Create FE hook for song playback

**__Technical Considerations__**
- TBD

**__Additional Considerations__**
- TBD

**Comment by angelopoole** [comment]
I started a feature branch for this, I should have something working tomorrow when I get the chance to work on it, at least a rough draft that allows me to play some music from a preset array.

I have gotten audio to play though so that's a plus +

Moving this over to the in-progress pipeline.

**Comment by jdmedlock** [comment]
@angelopoole expects to be finished today
